// Resume data structure
export const defaultResumeData = {
  name: '',
  address: '',
  mobile: '',
  email: '',
  github: '',
  linkedin: '',
  careerObjective: '',
  professionalQualifications: '',
  educationalQualifications: '',
  technicalSkill: '',
  title1: '',
  description1: '',
  role1: '',
  duration1: '',
  title2: '',
  description2: '',
  role2: '',
  duration2: '',
  coCurricularActivities: '',
  reward: '',
  certifications: '',
  strengths: '',
  areasOfImprovement: '',
  hobbies: '',
  areaOfInterest: '',
  dateOfBirth: '',
  gender: '',
  nationality: '',
  maritalStatus: '',
  language: '',
  motherTongue: '',
  fatherName: '',
  passwortDetails: '',
  permanentAddress: '',
  reference: '',
  declaration: '',
  currentDate: new Date().toLocaleDateString('en-IN'),
  place: '',
}